[settings]
midi-device-id = 3 # change it to the id of your midi keyboard
adaptive-volume = true # if true, the volume will be adjusted to the velocity of the note
volume = 50 # in percent

[sounds]
48 = "file1.mp3"
50 = "file2.mp3"